name: Compare functions
on: push
jobs:
  compare:
    runs-on: ubuntu-latest
    steps:
      - run: printenv | grep '_FUNC'
        env:
            CONTAINS_FUNC: ${{contains('Hello', 'ell')}}
            STARTS_WITH_FUNC: ${{startswith('Hello', 'He')}}
            ENDS_WITH_FUNC: ${{endswith('Hello', 'lo')}}
            